<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/unicorn.login.css');
$this->inlineScript()->appendFile($this->basePath() . '/js/unicorn.login.js');

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'loginorm');
$form->setAttribute('class', 'form-vertical');
?>
<div id="logo">
    <img src="/img/logo.png" alt="" />
</div>
<div id="loginbox">
    <?php echo $this->form()->openTag($form); ?>
    <div class="control-group">
        <?php
        $message = $this->formElementErrors($form->get('identity'));
        if (empty($message)) {
            $message = 'Enter username and password to continue';
        }
        ?>
        <p><?php echo $message; ?></p>
        <div class="controls">
            
            <div class="input-prepend">
                <span class="add-on"><i class="icon-user"></i></span><?php 
                    $identity = $form->get('identity');
                    $identity->setAttribute('placeholder', 'Password');
                    echo $this->formInput($identity) ?>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-lock"></i></span><?php
                    $credential = $form->get('credential');
                    $credential->setAttribute('placeholder', 'Password');
                    echo $this->formInput($credential) ?>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <span class="pull-right"><?php
            $button = $form->get('submit');
            $button->setAttribute('class', 'btn btn-inverse');
            echo $this->formButton($button);
      ?></span>
    </div>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>


<?php echo $this->form()->closeTag() ?>
</div>
<?php if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
